"""Initial version

Revision ID: 1cf93ebbd8b9
Revises: 
Create Date: 2026-06-16 14:50:30.385359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf93ebbd8b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_chats_created_at'), 'support_chats', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_chats_guest_email'), 'support_chats', ['guest_email'], unique=False)
    op.create_index(op.f('ix_support_chats_id'), 'support_chats', ['id'], unique=False)
    op.create_index(op.f('ix_support_chats_status'), 'support_chats', ['status'], unique=False)
    op.create_index(op.f('ix_support_chats_user_id'), 'support_chats', ['user_id'], unique=False)
    op.create_table('support_email_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['support_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_email_notifications_chat_id'), 'support_email_notifications', ['chat_id'], unique=False)
    op.create_index(op.f('ix_support_email_notifications_created_at'), 'support_email_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_email_notifications_id'), 'support_email_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_support_email_notifications_recipient_email'), 'support_email_notifications', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_support_email_notifications_status'), 'support_email_notifications', ['status'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['support_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_chat_id'), 'support_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_support_messages_created_at'), 'support_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_messages_id'), 'support_messages', ['id'], unique=False)
    op.create_index(op.f('ix_support_messages_is_read'), 'support_messages', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_messages_is_read'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_created_at'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_chat_id'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_support_email_notifications_status'), table_name='support_email_notifications')
    op.drop_index(op.f('ix_support_email_notifications_recipient_email'), table_name='support_email_notifications')
    op.drop_index(op.f('ix_support_email_notifications_id'), table_name='support_email_notifications')
    op.drop_index(op.f('ix_support_email_notifications_created_at'), table_name='support_email_notifications')
    op.drop_index(op.f('ix_support_email_notifications_chat_id'), table_name='support_email_notifications')
    op.drop_table('support_email_notifications')
    op.drop_index(op.f('ix_support_chats_user_id'), table_name='support_chats')
    op.drop_index(op.f('ix_support_chats_status'), table_name='support_chats')
    op.drop_index(op.f('ix_support_chats_id'), table_name='support_chats')
    op.drop_index(op.f('ix_support_chats_guest_email'), table_name='support_chats')
    op.drop_index(op.f('ix_support_chats_created_at'), table_name='support_chats')
    op.drop_table('support_chats')
    # ### end Alembic commands ###