"""Submissions add columns

Revision ID: 0be6c78360fd
Revises: dd145ea6c412
Create Date: 2026-05-05 15:16:48.725733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0be6c78360fd'
down_revision: Union[str, None] = 'dd145ea6c412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('submissions', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.alter_column('submissions', 'full_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('submissions', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_submissions_email'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_title'), table_name='submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_submissions_title'), 'submissions', ['title'], unique=False)
    op.create_index(op.f('ix_submissions_email'), 'submissions', ['email'], unique=False)
    op.alter_column('submissions', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('submissions', 'full_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('submissions', 'image_url')
    op.drop_column('submissions', 'excerpt')
    op.drop_column('submissions', 'category')
    # ### end Alembic commands ###
