"""Add bookmarks and user verification fields

Revision ID: 244f8561811c
Revises: af0543f1f3ef
Create Date: 2026-05-06 14:34:37.123798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244f8561811c'
down_revision: Union[str, None] = 'af0543f1f3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
