"""Add about table 0.3

Revision ID: 7d0e2684f4d4
Revises: 99bf48306816
Create Date: 2026-05-03 17:32:40.358881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0e2684f4d4'
down_revision: Union[str, None] = '99bf48306816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('main_content', sa.Text(), nullable=True),
    sa.Column('mission_statement', sa.Text(), nullable=True),
    sa.Column('team_description', sa.Text(), nullable=True),
    sa.Column('values_description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('newsroom_email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_page_id'), 'about_page', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_about_page_id'), table_name='about_page')
    op.drop_table('about_page')
    # ### end Alembic commands ###
