"""Fix Donation History

Revision ID: 9f47ff48c72a
Revises: fead571ec1dd
Create Date: 2026-05-11 17:30:41.004613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f47ff48c72a'
down_revision: Union[str, None] = 'fead571ec1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donor_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'donor_name')
    # ### end Alembic commands ###
