"""Add tags column to users table

Revision ID: a711e07451df
Revises: bf0a2965f9b9
Create Date: 2026-05-03 19:49:35.246782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a711e07451df'
down_revision: Union[str, None] = 'bf0a2965f9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('newsletter_subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'newsletter_subscribed')
    op.drop_column('users', 'tags')
    # ### end Alembic commands ###
