"""Fixes0.1

Revision ID: bf0a2965f9b9
Revises: e1080e5fc2d8
Create Date: 2026-05-03 18:20:33.835022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0a2965f9b9'
down_revision: Union[str, None] = 'e1080e5fc2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
