"""CardPeymentMethod

Revision ID: fead571ec1dd
Revises: c57af772f095
Create Date: 2026-05-11 16:38:57.553078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fead571ec1dd'
down_revision: Union[str, None] = 'c57af772f095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('donations', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('donations', sa.Column('order_id', sa.String(length=100), nullable=True))
    op.add_column('donations', sa.Column('liqpay_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('donations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'donations', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donations', type_='unique')
    op.drop_column('donations', 'updated_at')
    op.drop_column('donations', 'liqpay_transaction_id')
    op.drop_column('donations', 'order_id')
    op.drop_column('donations', 'status')
    op.drop_column('donations', 'currency')
    # ### end Alembic commands ###
